/**
 * Application Error Codes
 */

export const ERROR_CODES = {
  // Profile errors
  PROFILE_NOT_FOUND: 'PROFILE_NOT_FOUND',
  PROFILE_ALREADY_EXISTS: 'PROFILE_ALREADY_EXISTS',
  INVALID_PROFILE_DATA: 'INVALID_PROFILE_DATA',

  // Payday errors
  PAYDAY_NOT_SET: 'PAYDAY_NOT_SET',
  PAYDAY_PASSED: 'PAYDAY_PASSED',

  // Balance errors
  INSUFFICIENT_BALANCE: 'INSUFFICIENT_BALANCE',
  INVALID_BALANCE_AMOUNT: 'INVALID_BALANCE_AMOUNT',
  BALANCE_ADJUSTMENT_FAILED: 'BALANCE_ADJUSTMENT_FAILED',

  // Category errors
  CATEGORY_NOT_FOUND: 'CATEGORY_NOT_FOUND',
  INVALID_CATEGORY_DATA: 'INVALID_CATEGORY_DATA',
  CATEGORY_TYPE_MISMATCH: 'CATEGORY_TYPE_MISMATCH',
  CATEGORY_HAS_TRANSACTIONS: 'CATEGORY_HAS_TRANSACTIONS',
  INVALID_DAILY_CATEGORY: 'INVALID_DAILY_CATEGORY',

  // Transaction errors
  TRANSACTION_NOT_FOUND: 'TRANSACTION_NOT_FOUND',
  INVALID_TRANSACTION_DATA: 'INVALID_TRANSACTION_DATA',
  NEGATIVE_TRANSACTION_AMOUNT: 'NEGATIVE_TRANSACTION_AMOUNT',
  TRANSACTION_EDIT_FAILED: 'TRANSACTION_EDIT_FAILED',
  TRANSACTION_DELETE_FAILED: 'TRANSACTION_DELETE_FAILED',

  // Fixed expense errors
  FIXED_EXPENSE_NOT_FOUND: 'FIXED_EXPENSE_NOT_FOUND',
  FIXED_EXPENSE_ALREADY_PAID: 'FIXED_EXPENSE_ALREADY_PAID',
  FIXED_EXPENSE_NOT_PAID: 'FIXED_EXPENSE_NOT_PAID',
  FIXED_EXPENSE_REVERSE_FAILED: 'FIXED_EXPENSE_REVERSE_FAILED',
  INVALID_FIXED_EXPENSE_DATA: 'INVALID_FIXED_EXPENSE_DATA',

  // Forecast errors
  FORECAST_CALCULATION_FAILED: 'FORECAST_CALCULATION_FAILED',
  INSUFFICIENT_FOR_COMMITMENTS: 'INSUFFICIENT_FOR_COMMITMENTS',
  PROJECTED_NEGATIVE_BALANCE: 'PROJECTED_NEGATIVE_BALANCE',

  // Validation errors
  VALIDATION_FAILED: 'VALIDATION_FAILED',
  INVALID_REQUEST_DATA: 'INVALID_REQUEST_DATA',

  // General errors
  NOT_FOUND: 'NOT_FOUND',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  INVALID_OPERATION: 'INVALID_OPERATION',

  // Development errors
  DEVELOPMENT_ENDPOINTS_NOT_AVAILABLE: 'DEVELOPMENT_ENDPOINTS_NOT_AVAILABLE',};



